name: saltstack-aptcacherng-formula
source: https://github.com/bechtoldt/saltstack-aptcacherng-formula
summary: SaltStack Formula to set up and configure apt-cacher-ng, a caching proxy for software packages
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
